### ISSUE TITLE
psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  the database system is in recovery mode

### ISSUE THREAD

**Issue by nkPit** [okbob/plpgsql_check#162]
If in the folder with plpgsql_check, execute:
`echo test: all all all all all all all all all all all all all all all all > sch`

Create a file named all.sql in the sql folder:
```sql 
cat sql/all.sql
load 'plpgsql';
load 'plpgsql_check';
set client_min_messages to notice;-- enforce context's displaying
-- emulate pre 9.6 behave\set SHOW_CONTEXT alwaysset plpgsql_check.mode = 'every_start';create table t1(a int, b int);create function f1()
returns void as $$
begin
  if false then
    update t1 set c = 30;
  end if;
end;
$$ language plpgsql;select f1();drop function f1();
```

Add to Makefile:
`REGRESS = --schedule=sch`

After that, execute:
`for i in $(seq 10); do make installcheck; done
`
I get `psql: error: connection to server on socket "/tmp/.s.PGSQL.5432" failed: FATAL:  the database system is in recovery mode`
This is reproducible on the REL_15_STABLE, REL_16_STABLE branches.

**Comment by nkPit** [comment]
Or if you do it like this
`cat sql/*.sql >> sql/all.sql`
`echo ‘’ >expected/all.out`
`echo test: all all all all all all all all all all all all all all all all > sch`
Add to Makefile:
`REGRESS = --schedule=sch`
`for i in $(seq 10); do make installcheck; done `
Then we get:
`(test process exited with exit code 2)`

**Comment by okbob** [comment]
should be fixed by f6080ee9a06d25811f10b19b84065ca1917509c7 
please, check

**Comment by nkPit** [comment]
No. I'm still getting the same error. plpgsql_check(master), Postgres(REL_16_STABLE). 
If it helps:
`#0  0x00007f8806b89d33 in list_nth_cell (list=0x0, n=0)
    at /home/test/pgpro/include/postgresql/server/nodes/pg_list.h:281
281		return &list->elements[n];
b(gdb) bt
#0  0x00007f8806b89d33 in list_nth_cell (list=0x0, n=0)
    at /home/test/pgpro/include/postgresql/server/nodes/pg_list.h:281
#1  0x00007f8806b8a882 in ExprGetQuery (cstate=0x7ffe2a18f2c0, expr=0x559ca90923e0)
    at src/check_expr.c:418
#2  0x00007f8806b8a3f3 in prepare_plan (cstate=0x7ffe2a18f2c0, expr=0x559ca90923e0, cursorOptions=0,
    parser_setup=0x0, arg=0x0) at src/check_expr.c:278
#3  0x00007f8806b8c2c1 in plpgsql_check_expr_as_rvalue (cstate=0x7ffe2a18f2c0, expr=0x559ca90923e0,
    targetrec=0x0, targetrow=0x0, targetdno=1, use_element_type=false, is_expression=true)
    at src/check_expr.c:1212
#4  0x00007f8806b8d504 in plpgsql_check_assignment (cstate=0x7ffe2a18f2c0, expr=0x559ca90923e0,
    targetrec=0x0, targetrow=0x0, targetdno=1) at src/check_expr.c:1691
#5  0x00007f8806ba4cdb in plpgsql_check_stmt (cstate=0x7ffe2a18f2c0, stmt=0x559ca90923a8,
    closing=0x7ffe2a18eb80, exceptions=0x7ffe2a18eb88) at src/stmtwalk.c:431
#6  0x00007f8806ba739c in check_stmts (cstate=0x7ffe2a18f2c0, stmts=0x559ca9092480,
    closing=0x7ffe2a18f1a8, exceptions=0x7ffe2a18f1b0) at src/stmtwalk.c:1360
#7  0x00007f8806ba45a9 in plpgsql_check_stmt (cstate=0x7ffe2a18f2c0, stmt=0x559ca9092848,
    closing=0x7ffe2a18f1a8, exceptions=0x7ffe2a18f1b0) at src/stmtwalk.c:258
#8  0x00007f8806b8e446 in passive_check_func_beg (estate=0x7ffe2a18f5d0, func=0x559ca9032c68,
    plugin2_info=0x559ca90abe60) at src/check_function.c:417
#9  0x00007f8806b9bb51 in pldbgapi2_func_beg (estate=0x7ffe2a18f5d0, func=0x559ca9032c68)
    at src/pldbgapi2.c:963
#10 0x00007f8806bd5006 in plpgsql_exec_function () from /home/test/pgpro/lib/postgresql/plpgsql.so
#11 0x00007f8806bde983 in plpgsql_call_handler () from /home/test/pgpro/lib/postgresql/plpgsql.so
#12 0x0000559ca6d532c1 in fmgr_security_definer ()
#13 0x0000559ca6a82d33 in ExecInterpExpr ()
--Type <RET> for more, q to quit, c to continue without paging--
#14 0x0000559ca6ab4661 in ExecResult ()
#15 0x0000559ca6a868b2 in standard_ExecutorRun ()
#16 0x0000559ca6c1f6bf in PortalRunSelect ()
#17 0x0000559ca6c20aa3 in PortalRun ()
#18 0x0000559ca6c1cf8d in exec_simple_query ()
#19 0x0000559ca6c1f0c7 in PostgresMain ()
#20 0x0000559ca6b99a4a in ServerLoop ()
#21 0x0000559ca6b9aa32 in PostmasterMain ()
#22 0x0000559ca68f2181 in main ()`

**Comment by okbob** [comment]
please check 6e0462ff5d2c5770f648338cc06eebaba8f4993d

**Comment by nkPit** [comment]
Everything is working. Thanks for corrections!

**Comment by okbob** [comment]
thank you for bug report
